# Generated by Django 4.0.2 on 2022-02-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
